name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --no-cache-dir -r requirements.txt

      - name: Compile application
        run: |
          source .venv/bin/activate
          python -m py_compile app.py

      - name: Test application
        run: |
          source .venv/bin/activate
          python -c "import app; print(app.health())"
          
            
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::152439496947:role/GitHubActionsECRRole
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login \
            --username AWS \
            --password-stdin 152439496947.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t jenkins-python-demo:${{ github.sha }} .

      - name: Tag Docker image
        run: |
          docker tag \
            jenkins-python-demo:${{ github.sha }} \
            152439496947.dkr.ecr.ap-south-1.amazonaws.com/jenkins-python-demo:${{ github.sha }}

      - name: Push Docker image to ECR
        run: |
          docker push \
            152439496947.dkr.ecr.ap-south-1.amazonaws.com/jenkins-python-demo:${{ github.sha }}
